name: Docker Build Caller

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-app:
    uses: ./.github/workflows/build-image.yml
    with:
      image-name: app
      target: go_deploy
      create-attestation: true
    secrets: inherit

  build-filter:
    uses: ./.github/workflows/build-image.yml
    with:
      image-name: filter
      target: filter_deploy
      create-attestation: true
    secrets: inherit
