name: Build Caller

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build-app:
    needs: setup
    uses: ./.github/workflows/build-image.yml
    with:
      image-name: app
      target: go_deploy
    secrets: inherit

  build-filter:
    needs: setup
    uses: ./.github/workflows/build-image.yml
    with:
      image-name: filter
      target: filter_deploy
    secrets: inherit
